### ISSUE TITLE
Tapeutils doesn't build with Cygwin

### ISSUE THREAD

**Issue by jfcl** [brouhaha/tapeutils#15]
Simple obvious fix attached.

<pre>
$ git diff -u read20.c
diff --git a/read20.c b/read20.c
index 92ee00a..b152bf7 100644
--- a/read20.c
+++ b/read20.c
@@ -86,7 +86,7 @@ char *expression = 0;
 char *re_comp_error;     /* Error message from re_comp() */
 extern char *re_comp();

-#if defined(__APPLE__) || defined(__OpenBSD__)
+#if defined(__APPLE__) || defined(__OpenBSD__) || defined(__CYGWIN__)
 static regex_t re_regexp;

 char *re_comp(char *s)
<pre>

**Comment by jfcl** [comment]
Submitted pull request https://github.com/brouhaha/tapeutils/pull/14

**Comment by larsbrinkhoff** [comment]
Merged; thanks!
